# Generated by Django 3.1.12 on 2021-09-21 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=1000)),
                ('date_crate', models.DateField(auto_now_add=True)),
                ('company', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='companies.companies')),
            ],
        ),
    ]
