# Generated by Django 3.1.12 on 2021-09-21 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('New', 'new'), ('InProgress', 'in progress'), ('Done', 'done')], default='New', max_length=20)),
                ('priority', models.CharField(choices=[('LP', 'low priority'), ('MP', 'medium priority'), ('HP', 'high priority')], default='LP', max_length=20)),
                ('type_task', models.CharField(choices=[('Software', 'software'), ('Information', 'information'), ('Consulting', 'consulting'), ('Product', 'product')], default='', max_length=20)),
                ('date_crate', models.DateField(auto_now_add=True)),
                ('dead_line', models.DateField()),
                ('coast', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contacts.contacts')),
                ('executor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='projects.projects')),
            ],
        ),
    ]
