version: '3.7'

services:
  web:
    build: ./crm
    command: bash -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./crm/:/usr/src/crm/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=230961
      - POSTGRES_DB=crm_workdb

volumes:
  postgres_data: