# Generated by Django 3.1.12 on 2021-09-21 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('position', models.CharField(max_length=30)),
                ('sex', models.CharField(choices=[('M', 'male'), ('F', 'female'), ('O', 'other')], default='', max_length=20)),
                ('profile_image', models.ImageField(blank=True, default='default-avatar.png', null=True, upload_to='clients/')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='companies.companies')),
            ],
        ),
    ]
